title: "About Me- Libby Berkhout"
description: "Personal website for research, publications, and teaching."

url: "https://lmberkhout.github.io"
baseurl: ""

header_pages:
  - index.md
  - research.md
  - teaching.md

style: dark
footer: ""

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
